### ISSUE TITLE
Add a tab to see all downloads / tasks

### ISSUE THREAD

**Issue by XPoppyX** [agalwood/Motrix#748] opened 2020-07-19 19:57 UTC
Add a tab to see all the downloads that are in the state: downloading, waiting and stopped

![concept](https://user-images.githubusercontent.com/61259627/87883825-0b6c7e80-c9d8-11ea-8bf5-c61069477f53.png)

by the way, shouldn't it be: "paused" instead of "waiting"?
and "Completed" instead of "stopped"?

**Comment by mamal72** [comment] 2020-07-23 01:38
Dupe of https://github.com/agalwood/Motrix/issues/188, Related to https://github.com/agalwood/Motrix/pull/192.

**Closed** 2020-07-23 01:42 UTC
Labels: enhancement ✨
